### ISSUE TITLE
你这个可以做代理服务器吗

### ISSUE THREAD

**Issue by wgd12389** [Hucy/mocksever#4]
如果我想请求远程的服务器，避免跨域的问题，通过你这个server做转发的话，那么我怎么用呢，比如我除了配置apihost之外，还需要做什么

**Comment by wgd12389** [comment]
兄弟，这个代理的搞明白了，不过建议你在https://github.com/Hucy/mocksever/blob/master/mockroute/index.js这个文件的第67行catch中加上异常的打印，要不然发生异常了，你的提示是走了本地的请求接口，如果不看源码，不加上异常的打印，我甚至都不知道我的请求地址写错了，所以这种异常的提示还是挺重要的

**Comment by Hucy** [comment]
好的，回去处理下 。
这个代理只能代理到json 数据，是为了和后端协同开发用的
如果要代理静态数据的 比如 js css img 的话，建议在webpack的devserver 中配置 代理
